# NAMESPACES
namespaces:
  TimeStick_ns:
    hardware:       "OCP-TAP_TimeStick"
    IP/mask:        "10.102.0.10/24"
    gateway:        "10.102.0.1"
    interface:      "enxc8a3627c5084"
    pps_mode:       "INDEF"
  Intel710_ns:
    hardware:       "Intel710"
    IP/mask:        "10.103.0.10/24"
    gateway:        "10.103.0.1"
    interface:      "enp52s0f0np0"
    pps_mode:       "OUT"
  Intel810_ns:
    hardware:       "Intel810"
    IP/mask:        "10.104.0.10/24"
    gateway:        "10.104.0.1"
    interface:      "enp112s0f0np0"
    pps_mode:       "OUT"

# PTP PARAMETERS
ptp_clients:
  TimeStick:
    config: TimeStick.conf
    namespace: TimeStick_ns
    interface: enxc8a3627c5084
  Intel710:
    config: Intel710.conf
    namespace: Intel710_ns
    interface: enp52s0f0np0
  Intel810:
    config: Intel810.conf
    namespace: Intel810_ns
    interface: enp112s0f0np0

# TGEN STL PARAMETERS
loadgen_stl_program: "stl_Ly3_E1.py"
loadgen_stl_args:
  load_percentage: 25
  traffic_model: "TM1"
  port_list: "[0,1,2,3,4,5,6,7]"

# DEXT PARAMETERS
dataex_datasources:
  Intel710_PTP_Log:
    data_class: FileLogDataSource
    pattern: "master offset\\s+(?P<offset>-?\\d+)\\s+s2\\s+freq\\s+(?P<freq>[+-]?\\d+)\\s+path delay\\s+(?P<delay>\\d+)"
    filepath: ptp-Intel710.log
  TimeStick_PTP_Log:
    data_class: FileLogDataSource
    pattern: "master offset\\s+(?P<offset>-?\\d+)\\s+s2\\s+freq\\s+(?P<freq>[+-]?\\d+)\\s+path delay\\s+(?P<delay>\\d+)"
    filepath: ptp-TimeStick.log
  Intel810_PTP_Log:
    data_class: FileLogDataSource
    pattern: "master offset\\s+(?P<offset>-?\\d+)\\s+s2\\s+freq\\s+(?P<freq>[+-]?\\d+)\\s+path delay\\s+(?P<delay>\\d+)"
    filepath: ptp-Intel810.log
  PPSAnalyzer:
    data_class: PPSAnalyzerDataSource
    serial_port: "/dev/ttyUSB1"
    pps_inputs: [3,4,5]
    cable_delays: [0,0,0]

# EXPERIMENT PARAMETERS
synccore_start: -1
synccore_stop_at_end: false
loadgen_stl_start: 0
dataex_start: 60
total_duration: 7260
