dpdk_driver:    vfio-pci                # DPDK Driver for TRex
n_ports:        8

pci_bus_port0: "0000:16:00.0"           # PCI Bus Addres for Port 0
pci_bus_port1: "0000:16:00.1"           # PCI Bus Addres for Port 1
pci_bus_port2: "0000:16:00.2"           # PCI Bus Addres for Port 2
pci_bus_port3: "0000:16:00.3"           # PCI Bus Addres for Port 3
pci_bus_port4: "0000:52:00.0"           # PCI Bus Addres for Port 4
pci_bus_port5: "0000:52:00.1"           # PCI Bus Addres for Port 5
pci_bus_port6: "0000:52:00.2"           # PCI Bus Addres for Port 6
pci_bus_port7: "0000:52:00.3"           # PCI Bus Addres for Port 7