[global]
gmCapable               1
masterOnly              1
priority1               128
priority2               128
network_transport       UDPv4
domainNumber            0
inhibit_multicast_service   1
unicast_listen              1
unicast_req_duration    64800
tx_timestamp_timeout    1000
logging_level           6
verbose                 1
logAnnounceInterval     0
logSyncInterval         0
logMinDelayReqInterval  0

[enp112s0f0np0]
