# NAMESPACES
namespaces:
  Intel810_server_ns:
    hardware:       "Intel810"
    IP/mask:        "10.101.0.11/24"
    gateway:        "10.101.0.1"
    interface:      "enp112s0f0np0"
    pps_interface:  "enp112s0f0np0"
    pps_sma:        "SMA1"
    pps_mode:       "IN"
  Intel810_client_ns:
    hardware:       "Intel810"
    IP/mask:        "10.104.0.10/24"
    gateway:        "10.104.0.1"
    interface:      "enp112s0f2np2"
    pps_interface:  "enp112s0f0np0"
    pps_sma:        "SMA2"
    pps_mode:       "OUT"

# PTP PARAMETERS
ptp_clients:
  Intel810_server:
    config: preset_master.conf
    namespace: Intel810_server_ns
    interface: enp112s0f0np0
  Intel810_client:
    config: Intel810.conf
    namespace: Intel810_client_ns
    interface: enp112s0f2np2

# TGEN STL PARAMETERS
loadgen_stl_program: "stl_Ly3_E1.py"
loadgen_stl_args:
  load_percentage: 20
  traffic_model: "SPTM"
  port_list: "[0,1,2,3,4,5,6,7]"

# DEXT PARAMETERS
dataex_datasources:
  Intel810_PTP_Client_Log:
    data_class: FileLogDataSource
    pattern: "(?P<msg_type>up|down)\\s+local\\s(?P<ts_local>\\d+)\\s+remote\\s(?P<ts_remote>\\d+)"
    filepath: ptp-Intel810_client.log

# EXPERIMENT PARAMETERS
synccore_start: -1
synccore_stop_at_end: false
loadgen_stl_start: 0
dataex_start: 60
total_duration: 3660
output_filepath: "PTP_DELAY/PTP_DELAY_M1_L20-T60-SPTM"
